package es.ubu.lsi.common;

import java.io.Serializable;

/**
 * TIPOS DE MENSAJES QUE SE PUEDEN ENVIAR EN EL CHAT.
 * DEFINE LOS DIFERENTES TIPOS DE MENSAJES SOPORTADOS
 * POR EL SISTEMA DE CHAT.
 *
 * @author MARIO FLORES
 * @version 1.0
 * @since MARZO 2025
 */
public enum MessageType implements Serializable {

    /**
     * CUANDO UN CLIENTE INICIA SESION.
     * ENVIADO POR EL CLIENTE AL CONECTARSE AL SERVIDOR.
     */
    LOGIN,

    /**
     * CUANDO UN CLIENTE CIERRA SESION.
     * ENVIADO POR EL CLIENTE AL DESCONECTARSE.
     */
    LOGOUT,

    /**
     * MENSAJE DE TEXTO NORMAL ENTRE USUARIOS.
     * ES EL TIPO MAS COMUN DE MENSAJE EN EL CHAT.
     */
    MENSAJE,

    /**
     * MENSAJE DEL SISTEMA.
     * GENERADO POR EL SERVIDOR PARA NOTIFICACIONES.
     */
    SISTEMA,

    /**
     * MENSAJE PRIVADO DIRIGIDO A UN USUARIO CONCRETO.
     * SOLO LO RECIBE EL DESTINATARIO ESPECIFICADO.
     */
    PRIVADO,

    /**
     * MENSAJE PARA BLOQUEAR A UN USUARIO.
     * INDICA QUE NO SE DESEAN RECIBIR MENSAJES DE ESE USUARIO.
     */
    BAN,

    /**
     * MENSAJE PARA DESBLOQUEAR A UN USUARIO.
     * PERMITE VOLVER A RECIBIR MENSAJES DE UN USUARIO BLOQUEADO.
     */
    UNBAN;
}